### ISSUE TITLE
No Permission to Open Recordings Location / Files Not Created When Screen Recording

### ISSUE THREAD

**Issue by HelderFlame** [appaheadgmbh/support#47] opened 2024-11-03 03:12 UTC
Hello, I hope you are full recovered!
Today I bought all bundle with 4 apps and  PolyCapture through the Apple Store. All bundle is working very well but with PolyCapture version 1.6 still the same issue with me, as soon as I stop recording the same message appears to me. Im running Sequoia 15.1

Thank you so much

![Screenshot 2024-11-02 at 8 07 40 PM](https://github.com/user-attachments/assets/8fbb39cb-7fd3-41ea-ab24-d0dd359a5f1e)

**Comment by martinlexow** [comment] 2024-11-03 10:14
Hi @HelderFlame — you closed the thread right away: Is the issue still present, or were you able to solve it? 

The error message on your screenshot indicates that PolyCapture apparently can’t access or open the folder where your recordings are supposed to be saved. 

In the settings, under the “**Recording**” tab, you can check the path under “**Recordings Location**”. The default path is `~/Movies/PolyCapture/Recordings/`

![Screenshot 2024-11-03 at 11 13 37](https://github.com/user-attachments/assets/47d70658-e4c0-433e-b73d-6d40cd8d74f0)

**Comment by HelderFlame** [comment] 2024-11-03 16:22
HI Martin, I suppose that I can change the folder to record the files where I want, especially since I have an external HD for that. but ok...I can handle this.. take note that and add this new issue for your to do list!

The most important things is the record screen doesn't work properly......

I changed back Record Location  to original folder and message stop But still not working,  all files from screen record still with Zero bytes, actually there is none, the folder are created but there is nothing on there, is totally empty.

I notice after stop the record, the folder freeze about 30 seconds on Finder window. after waiting this the computer back to normal and the folder are empty.

 Thank you for your support
 
![Screenshot 2024-11-03 at 8 19 57 AM](https://github.com/user-attachments/assets/7cac051c-f812-4285-bfc3-0c433e0bcd04)

**Comment by martinlexow** [comment] 2024-11-25 13:55
There was/is [an issue](https://github.com/appaheadgmbh/support/issues/48) in the current version with screen recordings that were meant to capture a screen area on a _secondary_ monitor. 

Could this also be the cause of the case you described?

**Comment by martinlexow** [comment] 2024-12-04 15:07
Since, to my knowledge, the problem has not occurred for anyone since the recent updates, I assume the bug has been fixed and will therefore close this thread. Thank you again for your feedback, @HelderFlame!

**Closed as completed by martinlexow** 2024-12-04 15:07 UTC
Labels: Bug, ✓ Fixed, App: PolyCapture 📽️
