### ISSUE TITLE
Screen Recording: .mov file not compatible or can’t be opened

### ISSUE THREAD

**Issue by seiz** [appaheadgmbh/support#43] opened 2024-10-15 16:20 UTC
Hi,

using the demo mode to record, I have added one "Single Window" screen (I tried Safari and NetNewsWire - the App doesn't seem to matter) and Microphones etc.

After recording, can play all the recorded files in Quicktime Player except the recorded single window screen. When  I double-click the file, Finder displays an Error: 
![CleanShot 2024-10-15 at 18 11 46](https://github.com/user-attachments/assets/80d1cdf1-ebdb-43b2-bf75-ed7a397dcbdc)

This doesn't happen if I record the entire screen.

When I run "file" in terminal to analyse the .mov, this is what is reported: ISO Media, Apple QuickTime movie, Apple QuickTime (.MOV/QT)

So currently, I can't play back the recorded screen. 
User error or bug?

System Info: MBP M3, 24GB RAM, Sequoia 15.0.1 (German), PolyCapture 1.5 (17)

PS: this is a great APP, very well designed. Congrats!

**Comment by seiz** [comment] 2024-10-15 16:31
FYI: I just purchased "Recording Features". Behaviour is the same, so this is definitively not a limitation of using the App in Demo-Mode.

**Comment by tayiorbeii** [comment] 2024-10-22 16:40
@seiz I had this same issue, but managed to fix it by turning off the Screen & System Audio Recording preference, then opening the app again, then re-activating the permission, then relaunching the app again.

Hope this works for you too!

**Comment by seiz** [comment] 2024-10-22 16:58
@tayiorbeii Thanks a lot. Unfortunately this procedure didn't fix It for me.

**Comment by djpowers** [comment] 2024-10-23 02:42
Here to report the same issue. Trying to record a "Single Window" selection, camera feed and audio feed record properly, but resulting .mov file "cannot be opened." Further stating "The file isn’t compatible with QuickTime Player."

Currently running Sonoma 14.7. I tried toggling the screen & system audio recording permission, but it did not resolve the problem.

**Comment by czottmann** [comment] 2024-10-24 10:23
Same here. I ran the `.mov` file through ffmpeg, maybe this info helps:

```
❯ ffmpeg -i screen-CB69088B-1BB2-4112-935C-E826FCBCB680.mov out.mov
ffmpeg version 7.0.2 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.2_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x146704da0] moov atom not found
[in#0 @ 0x600000074100] Error opening input: Invalid data found when processing input
Error opening input file screen-CB69088B-1BB2-4112-935C-E826FCBCB680.mov.
Error opening input files: Invalid data found when processing input
```

If you need anything else to debug this issue, let me know. (macOS dev here.)

**Comment by martinlexow** [comment] 2024-10-24 12:34
Thanks to everyone for your detailed bug reports! I can confirm that, unfortunately, the issue can also be reproduced on my test devices (it’s not a limitation of the trial version). 

Unfortunately, I came down with COVID a little over a week ago and likely won’t be able to fix the issue until next week. I’ll keep you updated in this thread—sorry for the inconvenience!

**Comment by seiz** [comment] 2024-10-24 12:56
> Unfortunately, I came down with COVID a little over a week ago and likely won’t be able to fix the issue until next week. I’ll keep you updated in this thread—sorry for the inconvenience!

Ouch. Get well soon!

**Comment by czottmann** [comment] 2024-10-24 13:04
> COVID

No sweat, get better soon!

**Comment by martinlexow** [comment] 2024-10-30 07:21
[Version 1.6](https://apps.apple.com/app/id6504193234) has been on the App Store since this morning and should fix all issues with screen recording. Would you mind taking a look and sharing your feedback? 🙏 

PS: Thank you for your well wishes and patience—I’m on the road to recovery!

**Comment by seiz** [comment] 2024-10-30 10:54
Thanks a lot! I can successfully play back screen recordings now. Issue fixed.

**Comment by czottmann** [comment] 2024-10-30 11:18
Thanks, @martinlexow! It works as expected now.

**Comment by HelderFlame** [comment] 2024-11-03 03:14
Hello, I hope you are fully recovered!
Today I bought all bundle with 4 apps and  PolyCapture through the Apple Store. All bundle is working very well but with PolyCapture version 1.6 still the same issue with me, as soon as I stop recording the same message appears to me. Im running Sequoia 15.1
![Screenshot 2024-11-02 at 8 07 40 PM](https://github.com/user-attachments/assets/c1f44e11-8033-4b37-b3d3-411ea34e4799)


Thank you so much

**Comment by martinlexow** [comment] 2024-11-25 14:01
The cause of the originally discussed issue seems to be resolved—all recorded files can now be opened without problems and are error-free. 🥳 I will therefore close this issue.

The issue mentioned by @HelderFlame  is a different one, and I will continue to track it in [this thread](https://github.com/appaheadgmbh/support/issues/47).

**Closed as completed by martinlexow** 2024-11-25 14:01 UTC
Labels: Bug, ✓ Fixed, App: PolyCapture 📽️
