### ISSUE TITLE
No sound recorded via external microphone

### ISSUE THREAD

**Issue by RainerZufall9393** [appaheadgmbh/support#37] opened 2024-10-06 14:36 UTC
Hey Martin, I made a short recording yesterday where I recorded my external camera, my external microphone and my screen with screen sound.

Afterwards I saw that the external microphone was created as a file with the correct length, but when I played back the file, there was no sound.

PolyCapture V1.5

Mac:
MacBook Pro
13-inch, M1, 2020
macOS 15.0 (24A335)

Camera:
Sony Alpha 6600 → Elgato CamLink 4k → MacBook

Microphone:
Rode VideoMic NTG → LG Desktop → MacBook

**Comment by martinlexow** [comment] 2024-11-26 09:22
Hi @RainerZufall9393, please excuse my late reply! Could you let me know if the issue is still happening with the latest update (V1.7)? 

Unfortunately, you're the only one who has reported this problem so far. 

In the past updates, I made extensive improvements to the video and audio recording — it’s possible that this has resolved the issue you experienced.

**Comment by martinlexow** [comment] 2024-12-20 13:42
Since no further issues with microphone recording have been reported to me in the meantime, and I suspect that any issues were fixed with one of the recent updates, I will close this thread. Thank you again for your feedback!

**Closed as completed by martinlexow** 2024-12-20 13:42 UTC
Labels: Bug, ✓ Fixed, App: PolyCapture 📽️
