### ISSUE TITLE
No Video File Created When Recording Screen on Intel Mac

### ISSUE THREAD

**Issue by alotia** [appaheadgmbh/support#48] opened 2024-11-12 18:01 UTC
I have not needed to use PolyCapture lately, but when I tried it yesterday (to record a Zoom presentation) it only captured the audio and not the screen. This morning, I tried some experiments trying to record from YouTube and I am still seeing the same behaviour: Only the audio is captured.

![PolyCapture after recording](https://github.com/user-attachments/assets/385b7808-231d-4a73-b2bc-72a0bafe8659)

Here are the system details:

- MacOS 15.1 (on a 2019 Intel MacBook Pro)
- PolyCapture v1.6 (23)
- An external monitor (primary) and laptop acting as a second monitor.

All of the needed permissions are provided to PolyCapture
![PolyCapture permissions](https://github.com/user-attachments/assets/8df41ea9-e0d0-4849-aaca-c4e5fef519d6)

I have rebooted my system a couple of times, and I have uninstalled and reinstalled PolyCapture, but it is still behaving the same!  The one difference between when I first tried PolyCapture (and it worked okay) and now is that I have moved from Sonoma to Sequoia.

**Comment by AlexRVillalobos** [comment] 2024-11-13 16:37
Me too. No file created or recorded for Screen Area recording. 
Mac OS X Sequoia 15.1 (24B83)

**Comment by martinlexow** [comment] 2024-11-13 16:44
Thank you for your bug reports. 

Could it be that you tried to record a specific app window and that it wasn’t visible in the active space at the moment the recording started? Currently, that’s the only clue I can think of that might be causing the issue.

**Comment by AlexRVillalobos** [comment] 2024-11-13 16:46
Nio in my case

**Comment by alotia** [comment] 2024-11-13 17:06
My setup is a laptop screen (lid open) and an external monitor -- the external monitor is my primary screen and almost always where I am working. The session I wanted to record was playing on the laptop screen. PolyCapture was running on the primary screen, however, I had chosen the correct 'Single Window' from the drop-down menu.

I just retried a YouTube test, where I ran PolyCapture and the browser on the laptop's screen and I still don't get any video file; it only creates a '.caf' file.

**Comment by martinlexow** [comment] 2024-11-24 14:10
Quick update: Thank you for your detailed bug report, @alotia — I was able to identify the issue, am working on a fix, and hope to upload an update by the end of next week.

**Comment by martinlexow** [comment] 2024-11-24 14:13
One more note for a temporary workaround: The issue only occurs with multi-monitor setups. If only a single screen is used, capturing the screen area works.

**Comment by martinlexow** [comment] 2024-11-25 13:50
I was able to fix the issue today. A bug fix will be included in version 1.7 (which will ship asap).

**Comment by martinlexow** [comment] 2024-11-26 09:41
Version 1.7 is [now available](https://apps.apple.com/app/id6504193234) on the Mac App Store.

Please let me know if it resolves the issue on your end!

**Comment by AlexRVillalobos** [comment] 2024-11-26 09:48
I just updated and tried it, without success. It captured the audio from the webcam microphone fine, but it didn't capture a region of the screen. Also, when exporting to a directory with "Save as" the directory is empty.

[cid:C7738EC1E3F04DA3B1B810C963501845]
El 26 nov 2024, 10:42 +0100, Martin Lexow ***@***.***>, escribió:

Version 1.7 is now available<https://apps.apple.com/app/id6504193234?pt=60133800&ct=aaawebappcta> on the Mac App Store.

Please let me know if it resolves the issue on your end!

**Comment by martinlexow** [comment] 2024-11-26 10:02
Thanks for testing again @AlexRVillalobos. Could you perhaps send me a screenshot of your setup (like the one below)? 

The numbers (coordinates of the selected screen area) under each screen name should not contain negative values. Ideally, after the app update, it would be best to remove any previously set up screen areas and create new ones.

![Screenshot 2024-11-26 at 10 56 37](https://github.com/user-attachments/assets/72142c23-f17b-4d27-9ecc-ee1b020587b2)

If it’s still not working: To better understand the problem, it would also be helpful to know how your monitors are arranged (side by side, stacked, etc.).

**Comment by AlexRVillalobos** [comment] 2024-11-26 10:54
I have tried again, removing and re-enabling screenshot permissions; no success. Zero bytes, no recorded video file. Screenshots attached.

Thank you for your time and sorry for the inconvenience.

[cid:F758B6FBCB524BAF81F3972D6D0DAB1B][cid:040814FB10D04A2CBD463CFE2835BF13][cid:72BDECE864984CB1AD1701C98DE244EB]

[cid:F361E7571E204C4196993519B608B9A9][cid:D41AF1D1D3A649B987E00BFAB3702496]
El 26 nov 2024, 11:02 +0100, Martin Lexow ***@***.***>, escribió:

Thanks for testing again @AlexRVillalobos<https://github.com/AlexRVillalobos>. Could you perhaps send me a screenshot of your setup (like the one below)?

The numbers (coordinates of the selected screen area) under each screen name should not contain negative values. Ideally, after the app update, it would be best to remove any previously set up screen areas and create new ones.

Screenshot.2024-11-26.at.10.56.37.png (view on web)<https://github.com/user-attachments/assets/72142c23-f17b-4d27-9ecc-ee1b020587b2>

If it’s still not working: To better understand the problem, it would also be helpful to know how your monitors are arranged (side by side, stacked, etc.).

**Comment by martinlexow** [comment] 2024-11-26 14:52
Hi @AlexRVillalobos , unfortunately, your screenshot didn’t come through — could you possibly send it to me directly via email? → martin [at] appahead.studio

**Comment by AlexRVillalobos** [comment] 2024-11-26 14:57
sure, done.
El 26 nov 2024, 15:53 +0100, Martin Lexow ***@***.***>, escribió:

Hi @AlexRVillalobos<https://github.com/AlexRVillalobos> , unfortunately, your screenshot didn’t come through — could you possibly send it to me directly via email? → martin [at] appahead.studio

**Comment by alotia** [comment] 2024-11-26 16:44
Installed v1.7, and it hasn't fixed the problem for me, either. I have tried three tests:
- Record a screen area
- Record a single window
- Record the entire screen

Each of these only create only the .caf file. 

This is what the PolyCapture window looks like 
![PolyCapture Window](https://github.com/user-attachments/assets/c053bad8-00da-4b03-8a38-9a21c39be769)

**Comment by martinlexow** [comment] 2024-11-26 17:48
Thank you for your feedback and the screenshots — it seems like I might have solved a different (or the “wrong”) problem. I apologise for the circumstances!

At the moment, I don’t have any clues about what might be causing your issue. One last request, if you have a moment: In the folder of each recording, there is an (invisible) `.polycapture_meta` file. This file contains all the recording parameters (e.g., screen details) and would help me with debugging. Maybe one of you could send it to me?

![Screenshot 2024-11-26 at 18 40 11](https://github.com/user-attachments/assets/277149e3-052f-448f-8268-4aab2498e371)

Of course, I'll start looking into the issue even without the meta files, and I kindly ask for a bit more patience. Thank you so much in advance!

**Comment by alotia** [comment] 2024-11-26 18:01
I wasn't sure if these dot files contained any sensitive information. Instead of pasting them here, I have sent a couple of these dot files to your email.

**Comment by martinlexow** [comment] 2024-11-28 08:17
Thank you again for your support, @alotia & @AlexRVillalobos ! 🙏

I received the screenshots and meta files. Unfortunately, I couldn’t determine the cause of the issue from them.

Still, I released a [new app version](https://apps.apple.com/app/id6504193234) (1.8) today. In this version, any errors occurring before or during a recording should now be displayed. My request to you would be to install the update, try the screen recording again, and provide feedback on whether you received an error message (and if so, which one). 

I’m so sorry the app is causing you so much trouble — issues that I can’t reproduce are unfortunately particularly difficult to resolve. I hope this will help me get to the bottom of the issue.

**Comment by AlexRVillalobos** [comment] 2024-11-28 09:20
This new version and the previous one seem to work fine on OS X with M processors. I've tested it on M1 and M4.

The previous version didn't work well on Intel processors, apparently.
El 28 nov 2024, 9:18 +0100, Martin Lexow ***@***.***>, escribió:

Thank you again for your support, @alotia<https://github.com/alotia> & @AlexRVillalobos<https://github.com/AlexRVillalobos> ! 🙏

I received the screenshots and meta files. Unfortunately, I couldn’t determine the cause of the issue from them.

Still, I released a new app version<https://apps.apple.com/app/id6504193234> (1.8) today. In this version, any errors occurring before or during a recording should now be displayed. My request to you would be to install the update, try the screen recording again, and provide feedback on whether you received an error message (and if so, which one).

I’m so sorry the app is causing you so much trouble — issues that I can’t reproduce are unfortunately particularly difficult to resolve. I hope this will help me get to the bottom of the issue.

**Comment by alotia** [comment] 2024-11-28 15:56
I've tried two tests:
- Recording a single window
- Record the entire screen

In both cases, almost as soon as I press Record, I get this dialog:
![CleanShot 2024-11-28 at 07 55 18@2x](https://github.com/user-attachments/assets/e95a6aa9-3817-418d-a10b-06291b3763e4)

**Comment by martinlexow** [comment] 2024-11-29 08:38
Thank you for your tests! It seems the issue only occurs on Intel Macs. Unfortunately, I currently don’t have a suitable test Mac available—but I’ll try to test the app on one as soon as possible.

**Comment by martinlexow** [comment] 2024-12-01 13:57
I’ve just released a new update in the meantime ([V1.9](https://apps.apple.com/app/id6504193234)), which I believe fixes the screen recording issues on Intel Macs. 

Could you please check again to see if it works for you after the update? \*fingers crossed\*

**Comment by alotia** [comment] 2024-12-01 21:49
@martinlexow  I have tried a couple of tests: capturing a window and screen area and they both worked! Thank you for your persistence in chasing this issue.

**Comment by martinlexow** [comment] 2024-12-02 18:44
With that, the issue finally seems to be resolved (it also works reliably on other Intel Macs, which I was able to test myself now) — thank you so much for your support and patience! Without your detailed feedback @AlexRVillalobos @alotia , I wouldn’t have found the bug 🙏

**Closed as completed** 2024-12-04 15:05 UTC
Labels: Bug, ✓ Fixed, App: PolyCapture 📽️
