### ISSUE TITLE
PolyCapture microphone pause not possible

### ISSUE THREAD

**Issue by RainerZufall9393** [appaheadgmbh/support#39] opened 2024-10-06 14:42 UTC
Hey Martin, when I pause the recording in PolyCapture, only the video recording is paused, while the audio recording continues to run and does not interrupt.

PolyCapture Version 1.5

**Comment by martinlexow** [comment] 2024-10-09 12:44
Just to narrow down the issue: I assume you’re referring to audio recordings from microphones, and not from the screen, correct?

I reviewed the pause function on all my test devices today, double-checked the code, and had my internal TestFlight group verify it as well — unfortunately, we couldn’t reproduce the error. 

I suspected that you might have tried a very short pause, and interpreted the resulting different recording lengths ([as described here](https://github.com/appaheadgmbh/support/issues/38)) as an indication that the pause might not have worked. Could that be the case?

**Comment by RainerZufall9393** [comment] 2024-10-19 13:45
Hey Martin, sorry for the long response time.

Correct, I'm referring to the microphone recording, not the sound of the screen recording.

The pauses I tried were always several seconds long, sometimes even 10 seconds or more.

I will test it again later today and see if it still occurs and send you the recordings if necessary.

**Comment by RainerZufall9393** [comment] 2024-10-19 14:23
I have just tested it again and can no longer reproduce the bug. No idea what caused it. But I think we can consider it fixed for now. If the error occurs again in the future, I will contact you again. :)

**Comment by martinlexow** [comment] 2024-11-26 09:26
Glad to hear it’s working for you now! Since no one else has reported an issue with the pause function in the meantime, I assume the problem is resolved. I’ll go ahead and close this thread. Thank you for your feedback!

**Closed as completed by martinlexow** 2024-11-26 09:26 UTC
Labels: Bug, ✓ Fixed, App: PolyCapture 📽️
