### ISSUE TITLE
Microphone Recording Lost and Not Recording

### ISSUE THREAD

**Issue by wesbos** [appaheadgmbh/support#35] opened 2024-09-30 13:47 UTC
Several microphone recording issues, I've managed to capture them all in a single video:   https://share.cleanshot.com/GKT3T7dD

1. I am getting empty audio files (0-7kb) from my Volt 1 USB Interface microphone. The details for my Microphone interface that produces empty files are below.
2. Recording 4 microphones at once caused the recording to be lost - it never showed up in the recording UI
3. Recording multiple microphones at once causes the UI to remove the preview + × buttons. Likely a hover bug
4. 

Volt 1:2B5A:0020 /* Volt 1 */

<img width="516" alt="Screenshot 2024-09-30 at 9 32 11 AM" src="https://github.com/user-attachments/assets/ec66203a-20b7-4ff7-af4a-8c85b07db85f">

<img width="516" alt="Screenshot 2024-09-30 at 9 32 21 AM" src="https://github.com/user-attachments/assets/27cdfe0a-2d0f-41cf-9825-45e0ea1dda9c">

I have had issues with another Native Mac app (riverside) in the past where they did not set the HZ rate correctly for my microphone, so it sounded sped-up. Not sure if that is related or helpful.

**Comment by martinlexow** [comment] 2024-10-02 08:29
Thank you for the detailed bug report @wesbos — I was able to identify the cause of the issue and am working on a solution. It’s the [same issue described here](https://github.com/appaheadgmbh/support/issues/23), which is why I’d like to close this thread and continue the discussion there. I really appreciate that you’re taking so much time to test the app. Thanks again! 🙏

**Closed as completed by martinlexow** 2024-10-02 08:28 UTC
Labels: Bug, App: PolyCapture 📽️, Duplicate
